@startuml
skinparam actorStyle awesome
left to right direction

actor "Bibliothécaire" as user

rectangle "Application MediaTekDocuments" {
  usecase "Consulter les documents" as UC1
  usecase "Ajouter un document" as UC2
  usecase "Modifier un document (hors ID)" as UC3
  usecase "Supprimer un document" as UC4
  usecase "Vérifier absence d'exemplaires/commandes" as UC5
  
  UC4 ..> UC5 : <<include>>
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
@endum