@startuml
left to right direction
skinparam packageStyle rectangle

actor "Utilisateur" as user

rectangle "MediaTekDocuments - Sécurité" {
  usecase "S'authentifier" as UC_Auth
  usecase "Consulter les documents" as UC_Consul
  usecase "Gérer les commandes (Admin)" as UC_Admin
  usecase "Suivre les abonnements (Admin)" as UC_Alerte
  usecase "Accès refusé (Culture)" as UC_Refus
}

user --> UC_Auth
UC_Auth <.. UC_Consul : <<include>>
UC_Auth <.. UC_Admin : <<include>>
UC_Auth <.. UC_Alerte : <<include>>
UC_Auth <.. UC_Refus : <<include>>

note right of UC_Refus
  Entraîne la fermeture 
  de l'application
end note

note right of UC_Alerte
  Alerte proactive 
  réservée au service Administratif
end note
@enduml